server:
  port: 8001
# spring.application.name 用于指定注册到Eureka Server上的应用名称
spring:
  application:
    name: sc-eureka-first-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
 #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true